# Generated by Django 6.0.3 on 2026-03-05 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wristband',
            name='resident',
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('care_plan', models.TextField(blank=True)),
                ('medical_condition', models.TextField(help_text='Examples: dementia, learning disability, fall risk')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('medication_notes', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('favourite_activities', models.TextField(blank=True)),
                ('mobility_status', models.CharField(choices=[('independent', 'Independent'), ('assisted', 'Assisted'), ('wheelchair', 'Wheelchair')], default='independent', max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('family_member_name', models.CharField(blank=True, max_length=150)),
                ('family_member_contact', models.CharField(blank=True, max_length=20)),
                ('admission_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='tracker_ser_last_na_8e5285_idx'), models.Index(fields=['room_number'], name='tracker_ser_room_nu_3d97f2_idx'), models.Index(fields=['risk_level'], name='tracker_ser_risk_le_1371af_idx')],
            },
        ),
        migrations.CreateModel(
            name='WristbandDevice',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('bluetooth_mac_address', models.CharField(max_length=17, unique=True)),
                ('wristband_serial_number', models.CharField(max_length=100, unique=True)),
                ('battery_level', models.PositiveSmallIntegerField(help_text='Battery level percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signal_strength', models.IntegerField(help_text='RSSI value in dBm')),
                ('detector_sensor_id', models.CharField(max_length=64)),
                ('current_location', models.CharField(max_length=150)),
                ('previous_location', models.CharField(blank=True, max_length=150)),
                ('movement_status', models.CharField(choices=[('moving', 'Moving'), ('stationary', 'Stationary')], default='stationary', max_length=20)),
                ('last_detected_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('intermittent', 'Intermittent')], default='connected', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wristband_device', to='tracker.serviceuser')),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_location', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('signal_strength', models.IntegerField(help_text='RSSI value in dBm')),
                ('movement_detected', models.BooleanField(default=False)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='tracker.serviceuser')),
                ('wristband_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='tracker.wristbanddevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='DetectionEvent',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.DeleteModel(
            name='Wristband',
        ),
        migrations.AddIndex(
            model_name='wristbanddevice',
            index=models.Index(fields=['current_location'], name='tracker_wri_current_57efca_idx'),
        ),
        migrations.AddIndex(
            model_name='wristbanddevice',
            index=models.Index(fields=['last_detected_time'], name='tracker_wri_last_de_05a6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='wristbanddevice',
            index=models.Index(fields=['connection_status'], name='tracker_wri_connect_2a8cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['timestamp'], name='tracker_loc_timesta_3ed81d_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['detector_location'], name='tracker_loc_detecto_00df72_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['service_user', 'timestamp'], name='tracker_loc_service_bf6ef4_idx'),
        ),
    ]
