# Generated by Django 6.0.3 on 2026-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_wristband_resident_serviceuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wristbanddevice',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
