# Generated by Django 6.0.5 on 2026-05-07 00:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_wristbanddevice_rfid_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='signal_strength',
            field=models.IntegerField(default=0, help_text='RSSI value in dBm'),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='battery_level',
            field=models.PositiveSmallIntegerField(default=100, help_text='Battery level percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='current_location',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='detector_sensor_id',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='previous_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='wristbanddevice',
            name='signal_strength',
            field=models.IntegerField(default=0, help_text='RSSI value in dBm'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['wristband_device', 'timestamp'], name='tracker_loc_wristba_13631f_idx'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['wristband_device', 'signal_strength'], name='tracker_loc_wristba_2a78ec_idx'),
        ),
    ]
